// Import the necessary modules and functions
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";

import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import NextTopLoader from "nextjs-toploader";

//Define the Nunito font with different weights and subsets
const nunito = Nunito({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

//Define the metadata for the website
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Define the RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //Get the user ID using auth() function
  const { userId } = auth();

  //Use ClerkProvider to provide Clerk authentication context
  return (
    //Add language attribute to the HTML tag
    <html lang="en">
      //Add head tag with Nunito font link
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      //Add body tag with Nunito font class
      <body className={nunito.className}>
        Add NextTopLoader component with height, color, and easing attributes
        <NextTopLoader
          height={2}
          color="27AE60"
          easing="cubic-bezier(0.53,0.21,0,1)"
        />
        //Use ContextProvider and GlobalStyleProvider to provide context and
        styles
        <ContextProvider>
          <GlobalStyleProvider>
            //Display the Sidebar component if userId exists
            {userId && <Sidebar />}
            //Display the children prop in a div with full width
            <div className="w-full">{children}</div>
          </GlobalStyleProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
